{% set name = "dlltracer" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dlltracer-{{ version }}.tar.gz
  sha256: 7749c30d6372bfb3e5c1d624b0d5d05580b7fc3de92dfaa4f41ef1e5180d219c

build:
  number: 3
  skip: true  # [(not win) or (py<38)]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - pip
    - setuptools
    - python
    - pymsbuild
    - cython
  run:
    - python

test:
  imports:
    - dlltracer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/dlltracer-python
  summary: Python module for tracing Windows DLL loads
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
    - xhochy
