{% set name = "dlltracer" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dlltracer-{{ version }}.tar.gz
  sha256: 29a0987504e982b2d86ed7c89ae772037ec4ee70021177c26e3da28765213faa

build:
  number: 0
  skip: true  # [(not win) or (py<38)]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - pymsbuild
    - cython
  run:
    - python

test:
  imports:
    - dlltracer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/dlltracer-python
  summary: Python module for tracing Windows DLL loads
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
    - xhochy
