{% set name = "dlltracer" %}
{% set version = "0.1.0a3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dlltracer-{{ version }}.tar.gz
  sha256: 4a0ce30739a3313baebc9fe907cec7ba161b1052038acf5f1a306c133b3c82db

build:
  number: 0
  skip: true  # [(not win) or (py<38)]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - pymsbuild
    - cython
  run:
    - python

test:
  imports:
    - dlltracer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/dlltracer-python
  summary: Python module for tracing Windows DLL loads
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
