{% set name = "dlltracer" %}
{% set version = "1.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dlltracer-{{ version }}.tar.gz
  sha256: 4c31d5d0cf621caf4f3e2534b1dd9f2649ee10f39547be2c18f400698d3d31c7

build:
  number: 0
  skip: true  # [(not win) or (py<38)]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - pip
    - setuptools
    - python
    - pymsbuild
    - cython
  run:
    - python

test:
  imports:
    - dlltracer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/dlltracer-python
  summary: Python module for tracing Windows DLL loads
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
    - xhochy
